<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SpaServicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Deactivate the old demo SPA service 'test-spa'
        DB::table('spa_services')->where('slug', 'test-spa')->update(['status' => 0]);

        $packages = [
            [
                'title' => 'VIP Room Spa Package',
                'slug' => 'vip-room-spa-package',
                'duration_minutes' => 120,
                'price' => 50.00,
                'gender_type' => 'both',
                'status' => 1,
                'short_description' => 'Indulge in ultimate luxury with our VIP Spa Room package. Enjoy a private sauna, traditional Hamam ritual, private jacuzzi, a 45-minute relaxing massage, and a complimentary refreshment platter in complete privacy.',
                'description' => '<h3>Overview</h3><p>Experience the pinnacle of relaxation in our exclusive VIP Spa Room. This premium private package is designed for complete comfort and rejuvenation. You will have full access to your own private suite featuring a sauna, a luxurious Hamam with a full traditional scrub, foam massage, coconut peeling, and a nourishing face mask. Unwind further in your private jacuzzi before enjoying a soothing 45-minute full-body massage in a dedicated private massage room. To complete this indulgent experience, savor a refreshing plate of fresh fruits, juice, water, and biscuits served privately in your suite. Perfect for couples, special occasions, or anyone seeking a truly personalized and luxurious spa escape.</p><h3>Trip Highlights</h3><ul><li>Enjoy Private sauna session</li><li>Traditional Hamam ritual with scrub, foam massage, coconut peeling, and face mask</li><li>Enjoy Private Jacuzzi</li><li>45-minute full-body massage in a private room</li><li>Have a Refreshment platter of fruits, juice, water, and biscuits</li></ul><h3>Includes</h3><ul><li>Full private VIP Spa Room usage</li><li>Private Sauna</li><li>Private Hamam (scrub, foam massage, coconut peeling & face mask)</li><li>Private Jacuzzi session</li><li>45-minute professional massage</li><li>Plate of fresh fruits, juice, water & biscuits</li><li>All towels, robes, and spa amenities</li></ul><h3>Excludes</h3><ul><li>Additional massage time or treatments</li><li>Alcoholic beverages</li><li>Personal spa products</li><li>Transfer: $4/pax for Hurghada area, $5/pax for El Gouna/Sahl Hasheesh/Makadi, $7/pax for Safaga</li></ul>',
                'translations' => [
                    'ar' => [
                        'title' => 'باقة سبا الغرفة الخاصة (VIP)',
                        'short_description' => 'استمتع بالفخامة المطلقة مع باقة غرفة السبا الخاصة (VIP). استمتع بساونا خاصة، وطقوس الحمام التقليدي، وجاكوزي خاص، ومساج مريح لمدة 45 دقيقة، وطبق مرطبات مجاني في خصوصية تامة.',
                        'description' => '<h3>نظرة عامة</h3><p>اختبر قمة الاسترخاء في غرفة السبا الخاصة والحصرية (VIP). تم تصميم هذه الباقة الخاصة والمميزة لتوفير الراحة التامة وتجديد النشاط. ستحصل على دخول كامل إلى جناحك الخاص الذي يتميز بساونا، وحمام فاخر مع تقشير تقليدي كامل، ومساج بالرغوة، وتقشير بجوز الهند، وقناع مغذٍ للوجه. استرخِ أكثر في الجاكوزي الخاص بك قبل الاستمتاع بمساج مهدئ للجسم بالكامل لمدة 45 دقيقة في غرفة مساج خاصة مخصصة. لإكمال هذه التجربة الفاخرة، استمتع بطبق منعش من الفواكه الطازجة والعصير والماء والبسكويت الذي يقدم لك بشكل خاص في جناحك. مالي للأزواج، أو المناسبات الخاصة، أو أي شخص يبحث عن ملاذ سبا فاخر ومخصص حقًا.</p><h3>أبرز مميزات الرحلة</h3><ul><li>الاستمتاع بجلسة ساونا خاصة</li><li>طقوس الحمام التقليدي مع التقشير والمساج بالرغوة وتقشير جوز الهند وقناع الوجه</li><li>الاستمتاع بالجاكوزي الخاص</li><li>مساج كامل للجسم لمدة 45 دقيقة في غرفة خاصة</li><li>الحصول على طبق مرطبات من الفواكه والعصير والماء والبسكويت</li></ul><h3>يشتمل على</h3><ul><li>استخدام كامل لغرفة السبا الخاصة (VIP)</li><li>ساونا خاصة</li><li>حمام خاص (تقشير، مساج بالرغوة، تقشير جوز الهند وقناع الوجه)</li><li>جلسة جاكوزي خاصة</li><li>مساج احترافي لمدة 45 دقيقة</li><li>طبق من الفواكه الطازجة والعصير والماء والبسكويت</li><li>جميع المناشف والأرواب ومستلزمات السبا</li></ul><h3>لا يشتمل على</h3><ul><li>وقت مساج إضافي أو علاجات إضافية</li><li>المشروبات الكحولية</li><li>منتجات السبا الشخصية</li><li>الانتقالات: 4 دولارات للفرد لمنطقة الغردقة، 5 دولارات للفرد (الجونة - سهل حشيش - مكادي)، 7 دولارات لسفاجا</li></ul>',
                    ],
                    'de' => [
                        'title' => 'VIP-Raum Wellnesspaket',
                        'short_description' => 'Gönnen Sie sich ultimativen Luxus mit unserem VIP-Spa-Raum-Paket. Genießen Sie eine private Sauna, ein traditionelles Hamam-Ritual, einen privaten Whirlpool, eine 45-minütige Entspannungsmassage und eine kostenlose Erfrischungsplatte in absoluter Privatsphäre.',
                        'description' => '<h3>Überblick</h3><p>Erleben Sie den Gipfel der Entspannung in unserem exklusiven VIP-Spa-Raum. Dieses erstklassige private Paket ist auf vollkommenen Komfort und Verjüngung ausgelegt. Sie haben uneingeschränkten Zugang zu Ihrer eigenen privaten Suite mit Sauna, einem luxuriösen Hamam mit traditionellem Ganzkörperpeeling, Schaummassage, Kokosnuss-Peeling und einer pflegenden Gesichtsmaske. Entspannen Sie sich weiter in Ihrem privaten Whirlpool, bevor Sie eine wohltuende 45-minütige Ganzkörpermassage in einem eigenen privaten Massageraum genießen. Um dieses verwöhnende Erlebnis abzurunden, genießen Sie einen erfrischenden Teller mit frischem Obst, Saft, Wasser und Keksen, der Ihnen privat in Ihrer Suite serviert wird. Perfekt für Paare, besondere Anlässe oder alle, die ein wirklich persönliches und luxuriöses Spa-Erlebnis suchen.</p><h3>Highlights</h3><ul><li>Genießen Sie eine private Saunasitzung</li><li>Traditionelles Hamam-Ritual mit Peeling, Schaummassage, Kokosnuss-Peeling und Gesichtsmaske</li><li>Genießen Sie einen privaten Whirlpool</li><li>45-minütige Ganzkörpermassage in einem privaten Raum</li><li>Erfrischungsplatte mit Obst, Saft, Wasser und Keksen</li></ul><h3>Inklusive</h3><ul><li>Vollständige Nutzung des privaten VIP-Spa-Raums</li><li>Private Sauna</li><li>Privates Hamam (Peeling, Schaummassage, Kokosnuss-Peeling & Gesichtsmaske)</li><li>Private Whirlpool-Sitzung</li><li>45-minütige professionelle Massage</li><li>Teller mit frischem Obst, Saft, Wasser & Keksen</li><li>Alle Handtücher, Bademäntel und Spa-Annehmlichkeiten</li></ul><h3>Exklusive</h3><ul><li>Zusätzliche Massagezeit oder Behandlungen</li><li>Alkoholische Getränke</li><li>Persönliche Spa-Produkte</li><li>Transfer: $4/Person für das Gebiet Hurghada, $5/Person (El Gouna - Sahl Hasheesh - Makadi), $7/Person für Safaga</li></ul>',
                    ],
                    'fr' => [
                        'title' => 'Forfait Spa Salle VIP',
                        'short_description' => 'Offrez-vous le luxe ultime avec notre forfait VIP Spa Room. Profitez d\'un sauna privé, d\'un rituel de Hamam traditionnel, d\'un jacuzzi privé, d\'un massage relaxant de 45 minutes et d\'un plateau de rafraîchissements gratuit en toute intimité.',
                        'description' => '<h3>Aperçu</h3><p>Découvrez le summum de la relaxation dans notre salle de spa VIP exclusive. Ce forfait privé haut de gamme est conçu pour un confort et un rajeunissement complets. Vous aurez un accès complet à votre propre suite privée comprenant un sauna, un Hamam luxueux avec un gommage traditionnel complet, un massage à la mousse, un peeling à la noix de coco et un masque nourrissant pour le visage. Détendez-vous davantage dans votre jacuzzi privé avant de profiter d\'un massage apaisant de 45 minutes sur tout le corps dans une salle de massage privée dédiée. Pour compléter cette expérience indulgente, savourez une assiette rafraîchissante de fruits frais, de jus, d\'eau et de biscuits servis en privé dans votre suite. Parfait pour les couples, les occasions spéciales ou toute personne recherchant une escapade de spa véritablement personnalisée et luxueuse.</p><h3>Points Forts</h3><ul><li>Profitez d\'une séance de sauna privé</li><li>Rituel Hamam traditionnel avec gommage, massage à la mousse, peeling à la noix de coco et masque facial</li><li>Profitez d\'un jacuzzi privé</li><li>Massage complet du corps de 45 minutes dans une salle privée</li><li>Plateau de rafraîchissements composé de fruits, jus de fruits, eau et biscuits</li></ul><h3>Inclus</h3><ul><li>Utilisation complète de la salle de spa VIP privée</li><li>Sauna privé</li><li>Hamam privé (gommage, massage mousse, peeling coco & masque visage)</li><li>Séance de jacuzzi privé</li><li>Massage professionnel de 45 minutes</li><li>Assiette de fruits frais, jus, eau & biscuits</li><li>Toutes les serviettes, peignoirs et produits de spa</li></ul><h3>Exclus</h3><ul><li>Temps de massage ou traitements supplémentaires</li><li>Boissons alcoolisées</li><li>Produits de spa personnels</li><li>Transfert : 4$ par personne pour la zone de Hurghada, 5$ par personne (El Gouna - Sahl Hasheesh - Makadi), 7$ pour Safaga</li></ul>',
                    ],
                    'ru' => [
                        'title' => 'Спа-пакет VIP-зал',
                        'short_description' => 'Побалуйте себя непревзойденной роскошью с нашим спа-пакетом VIP Room. Наслаждайтесь частной сауной, традиционным ритуалом хамама, частным джакузи, 45-минутным расслабляющим массажем и бесплатной тарелкой с прохладительными напитками в полной конфиденциальности.',
                        'description' => '<h3>Обзор</h3><p>Испытайте пик расслабления в нашем эксклюзивном спа-салоне VIP Room. Этот приватный пакет премиум-класса создан для полного комфорта и омоложения. Вы получите полный доступ в свой собственный люкс с сауной, роскошным хамамом с полным традиционным пилингом, пенным массажем, кокосовым пилингом и питательной маской для лица. Отдохните еще немного в собственном джакузи, а затем насладитесь успокаивающим 45-минутным массажем всего тела в отдельном массажном кабинете. В завершение этого восхитительного вечера насладитесь освежающим ассорти из свежих фруктов, сока, воды и печенья, которое подадут прямо в ваш люкс. Идеально подходит для пар, особых случаев или тех, кто ищет по-настоящему персонализированный и роскошный спа-отдых.</p><h3>Основные моменты тура</h3><ul><li>Наслаждайтесь индивидуальным сеансом сауны</li><li>Традиционный ритуал хамама с пилингом, пенным массажем, кокосовым пилингом и маской для лица</li><li>Наслаждайтесь собственным джакузи</li><li>45-минутный массаж всего тела в отдельном кабинете</li><li>Тарелка с прохладительными напитками (фрукты, сок, вода, печенье)</li></ul><h3>В стоимость входит</h3><ul><li>Полное пользование приватным спа-кабинетом VIP-класса</li><li>Частная сауна</li><li>Приватный хамам (пилинг, пенный массаж, кокосовый пилинг и маска для лица)</li><li>Сеанс в гидромассажной ванне</li><li>45-минутный профессиональный массаж</li><li>Тарелка свежих фруктов, сок, вода и печенье</li><li>Все полотенца, халаты и спа-принадлежности</li></ul><h3>В стоимость не входит</h3><ul><li>Дополнительное время массажа или процедуры</li><li>Алкогольные напитки</li><li>Персональные спа-продукты</li><li>Трансфер: $4 с человека для Хургады, $5 с человека (Эль-Гуна - Сахл Хашиш - Макади), $7 для Сафаги</li></ul>',
                    ],
                    'tr' => [
                        'title' => 'VIP Oda Spa Paketi',
                        'short_description' => 'VIP Spa Odası paketimizle kendinizi olağanüstü bir lüksle ödüllendirin. Tamamen size özel bir alanda özel sauna, geleneksel Hamam ritüeli, özel jakuzi, 45 dakikalık rahatlatıcı masaj ve ücretsiz ikram tabağının keyfini çıkarın.',
                        'description' => '<h3>Genel Bakış</h3><p>Özel VIP Spa Odamızda rahatlamanın zirvesini yaşayın. Bu birinci sınıf özel paket, tam konfor ve gençleşme için tasarlanmıştır. Sauna, geleneksel kese, köpük masajı, hindistan cevizi peelingi ve besleyici yüz maskesi içeren lüks bir Hamam sunan kendi özel süitinize tam erişime sahip olacaksınız. Özel bir masaj odasında 45 dakikalık rahatlatıcı bir tam vücut masajının keyfini çıkarmadan önce özel jakuzinizde dinlenin. Bu şımartıcı deneyimi tamamlamak için süitinizde özel olarak servis edilen taze meyveler, meyve suyu, su ve bisküvilerden oluşan ferahlatıcı tabağın tadını çıkarın. Çiftler, özel günler veya gerçekten kişiselleştirilmiş ve lüks bir spa kaçamağı arayan herkes için mükemmeldir.</p><h3>Öne Çıkanlar</h3><ul><li>Özel sauna seansının keyfini çıkarın</li><li>Kese, köpük masajı, hindistan cevizi peelingi ve yüz maskesi içeren geleneksel Hamam ritüeli</li><li>Özel Jakuzi keyfi</li><li>Özel odada 45 dakikalık tam vücut masajı</li><li>Meyve, meyve suyu, su ve bisküviden oluşan ikram tabağı</li></ul><h3>Dahil Olanlar</h3><ul><li>Tamamen özel VIP Spa Odası kullanımı</li><li>Özel Sauna</li><li>Özel Hamam (kese, köpük masajı, hindistan cevizi peelingi ve yüz maskesi)</li><li>Özel Jakuzi seansı</li><li>45 dakikalık profesyonel masaj</li><li>Taze meyve tabağı, meyve suyu, su ve bisküviler</li><li>Tüm havlular, bornozlar ve spa olanakları</li></ul><h3>Hariç Olanlar</h3><ul><li>Ek masaj süresi veya tedaviler</li><li>Alkollü içecekler</li><li>Kişisel spa ürünleri</li><li>Transfer: Hurghada bölgesi için kişi başı 4$, El Gouna - Sahl Hasheesh - Makadi için kişi başı 5$, Safaga için kişi başı 7$</li></ul>',
                    ],
                    'hi' => [
                        'title' => 'वीआईपी रूम स्पा पैकेज',
                        'short_description' => 'हमारे वीआईपी स्पा रूम पैकेज के साथ परम विलासिता का आनंद लें। पूर्ण गोपनीयता में एक निजी सौना, पारंपरिक हमाम अनुष्ठान, निजी जकूज़ी, 45 मिनट की आरामदायक मालिश और एक मानार्थ जलपान थाली का आनंद लें।',
                        'description' => '<h3>अवलोकन</h3><p>हमारे विशेष वीआईपी स्पा रूम में विश्राम के शिखर का अनुभव करें। यह प्रीमियम निजी पैकेज पूर्ण आराम और कायाकल्प के लिए डिज़ाइन किया गया है। आपके पास सौना, पारंपरिक स्क्रब, फोम मसाज, नारियल छीलने और एक पौष्टिक फेस मास्क की विशेषता वाले अपने निजी सुइट तक पूर्ण पहुंच होगी। एक समर्पित निजी मालिश कक्ष में सुखदायक 45 मिनट की फुल-बॉडी मालिश का आनंद लेने से पहले अपने निजी जकूज़ी में आराम करें। इस अनुभव को पूरा करने के लिए, अपने सुइट में निजी तौर पर परोसे जाने वाले ताजे फल, जूस, पानी और बिस्कुट की ताज़ा प्लेट का स्वाद लें। जोड़ों, विशेष अवसरों, या वास्तव में व्यक्तिगत और शानदार स्पा अनुभव की तलाश करने वाले किसी भी व्यक्ति के लिए बिल्कुल सही।</p><h3>मुख्य आकर्षण</h3><ul><li>निजी सौना सत्र का आनंद लें</li><li>स्क्रब, फोम मसाज, कोकोनट पीलिंग और फेस मास्क के साथ पारंपरिक हमाम अनुष्ठान</li><li>निजी जकूज़ी का आनंद लें</li><li>निजी कमरे में 45 मिनट की फुल-बॉडी मसाज</li><li>फल, जूस, पानी और बिस्कुट की जलपान थाली</li></ul><h3>शामिल है</h3><ul><li>पूर्ण निजी वीआईपी स्पा रूम का उपयोग</li><li>निजी सौना</li><li>निजी हमाम (स्क्रб, फोम मसाज, नारियल छीलने और फेस मास्क)</li><li>निजी जकूज़ी सत्र</li><li>45 मिनट की व्यावसायिक मालिश</li><li>ताजे फल, जूस, पानी और बिस्कुट की प्लेट</li><li>सभी तौलिये, गाउन और स्पा सुविधाएं</li></ul><h3>बाहर रखा गया</h3><ul><li>अतिरिक्त मालिश समय या उपचार</li><li>मादक पेय</li><li>व्यक्तिगत स्पा उत्पाद</li><li>स्थानांतरण: हुर्गदा क्षेत्र के लिए $4 प्रति व्यक्ति, $5 प्रति व्यक्ति (एल-गोना - साहल हशीश - मकाडी), $7 सफागा</li></ul>',
                    ]
                ]
            ],
            [
                'title' => 'Cleopatra Plus Package',
                'slug' => 'cleopatra-plus-package',
                'duration_minutes' => 120,
                'price' => 26.00,
                'gender_type' => 'both',
                'status' => 1,
                'short_description' => 'Indulge in the luxurious Cleopatra Plus experience featuring a salt cave, sauna, steam room, jacuzzi, full traditional scrub & foam massage, coconut peeling with face mask, and a relaxing 45-minute massage.',
                'description' => '<h3>Overview</h3><p>Treat yourself to the ultimate Cleopatra-inspired spa journey with our exclusive Cleopatra Plus package. This comprehensive wellness experience combines ancient relaxation rituals with modern comfort for complete rejuvenation. Begin in the therapeutic Salt Cave, followed by sessions in the Sauna and Steam Room. Unwind in the soothing Private Jacuzzi, then enjoy a full traditional Hamam ritual including a deep body scrub, rich foam massage, gentle coconut peeling, and a nourishing face mask. The experience concludes with a blissful 45-minute full-body massage to melt away stress and leave you refreshed and glowing. Perfect for those seeking a deep cleansing, relaxing, and luxurious spa day.</p><h3>Trip Highlights</h3><ul><li>Therapeutic session in the Salt Cave</li><li>Sauna and Steam Room for deep detoxification</li><li>Relaxing soak in the private jacuzzi</li><li>Traditional scrub, foam massage, coconut peeling, and face mask</li><li>Soothing 45-minute full-body massage</li></ul><h3>Includes</h3><ul><li>Salt Cave session</li><li>Sauna & Steam Room</li><li>Private Jacuzzi</li><li>Full Traditional Scrub & Foam Massage</li><li>Coconut Peeling with Face Mask</li><li>45-minute Professional Massage</li><li>All towels, robes, and spa essentials</li></ul><h3>Excludes</h3><ul><li>Additional treatments or extended massage time</li><li>Alcoholic or premium beverages</li><li>Personal spa products</li><li>Transfer: $4/pax for Hurghada area, $5/pax for El Gouna/Sahl Hasheesh/Makadi, $7/pax for Safaga</li></ul>',
                'translations' => [
                    'ar' => [
                        'title' => 'باقة كليوباترا بلس',
                        'short_description' => 'استمتع بتجربة كليوباترا بلس الفاخرة التي تتميز بكهف الملح، الساونا، غرفة البخار، الجاكوزي، التقشير التقليدي الكامل والمساج بالرغوة، تقشير جوز الهند مع قناع الوجه، ومساج مريح لمدة 45 دقيقة.',
                        'description' => '<h3>نظرة عامة</h3><p>دلل نفسك برحلة السبا المستوحاة من كليوباترا مع باقة كليوباترا بلس الحصرية. تجمع هذه التجربة الصحية الشاملة بين طقوس الاسترخاء القديمة ووسائل الراحة الحديثة لتجديد النشاط بالكامل. ابدأ في كهف الملح العلاجي، تليها جلسات في الساونا وغرفة البخار. استرخِ في الجاكوزي الخاص المهدئ، ثم استمتع بطقوس الحمام التقليدي الكامل بما في ذلك تقشير الجسم العميق والمساج بالرغوة الغنية وتقشير جوز الهند اللطيف وقناع الوجه المغذي. تنتهي التجربة بمساج مبهج للجسم بالكامل لمدة 45 دقيقة لإزالة التوتر وتركك منتعشًا ومشرقًا. مثالي لمن يبحثون عن تنظيف عميق واسترخاء ويوم سبا فاخر.</p><h3>أبرز مميزات الرحلة</h3><ul><li>جلسة علاجية في كهف الملح</li><li>ساونا وغرفة بخار للتخلص من السموم بعمق</li><li>نقع مريح في الجاكوزي الخاص</li><li>تقشير تقليدي ومساج بالرغوة وتقشير بجوز الهند وقناع للوجه</li><li>مساج مهدئ للجسم بالكامل لمدة 45 دقيقة</li></ul><h3>يشتمل على</h3><ul><li>جلسة كهف الملح</li><li>ساونا وغرفة بخار</li><li>جاكوزي خاص</li><li>تقشير كامل ومساج بالرغوة تقليدي</li><li>تقشير بجوز الهند مع قناع للوجه</li><li>مساج احترافي لمدة 45 دقيقة</li><li>جميع المناشف والأرواب ومستلزمات السبا الأساسية</li></ul><h3>لا يشتمل على</h3><ul><li>علاجات إضافية أو وقت مساج إضافي</li><li>المشروبات الكحولية أو الفاخرة</li><li>منتجات السبا الشخصية</li><li>الانتقالات: 4 دولارات للفرد لمنطقة الغردقة، 5 دولارات للفرد (الجونة - سهل حشيش - مكادي)، 7 دولارات لسفاجا</li></ul>',
                    ],
                    'de' => [
                        'title' => 'Cleopatra Plus Paket',
                        'short_description' => 'Gönnen Sie sich das luxuriöse Cleopatra Plus-Erlebnis mit einer Salzgrotte, Sauna, Dampfbad, Whirlpool, traditioneller Ganzkörperpeeling- und Schaummassage, Kokospeeling mit Gesichtsmaske und einer entspannenden 45-minütigen Massage.',
                        'description' => '<h3>Überblick</h3><p>Gönnen Sie sich die ultimative, von Cleopatra inspirierte Spa-Reise mit unserem exklusiven Cleopatra Plus-Paket. Dieses umfassende Wellness-Erlebnis kombiniert alte Entspannungsrituale mit modernem Komfort für vollkommene Verjüngung. Beginnen Sie in der therapeutischen Salzgrotte, gefolgt von Sitzungen in der Sauna und im Dampfbad. Entspannen Sie sich im wohltuenden privaten Whirlpool und genießen Sie anschließend ein traditionelles Hamam-Ritual mit einem tiefen Körperpeeling, einer reichhaltigen Schaummassage, einem sanften Kokospeeling und einer nährenden Gesichtsmaske. Das Erlebnis endet mit einer wohltuenden 45-minütigen Ganzkörpermassage, die Stress abbaut und Sie erfrischt und strahlend zurücklässt. Perfekt für alle, die eine Tiefenreinigung, Entspannung und einen luxuriösen Wellness-Tag suchen.</p><h3>Highlights</h3><ul><li>Therapeutische Sitzung in der Salzgrotte</li><li>Sauna und Dampfbad zur tiefen Entgiftung</li><li>Entspannendes Bad im privaten Whirlpool</li><li>Traditionelles Peeling, Schaummassage, Kokospeeling und Gesichtsmaske</li><li>Wohltuende 45-minütige Ganzkörpermassage</li></ul><h3>Inklusive</h3><ul><li>Sitzung in der Salzgrotte</li><li>Sauna & Dampfbad</li><li>Privater Whirlpool</li><li>Traditionelle Peeling- & Schaummassage</li><li>Kokospeeling mit Gesichtsmaske</li><li>45-minütige professionelle Massage</li><li>Alle Handtücher, Bademäntel und Spa-Essentials</li></ul><h3>Exklusive</h3><ul><li>Zusätzliche Behandlungen oder verlängerte Massagezeit</li><li>Alkoholische Getränke oder Premium-Getränke</li><li>Persönliche Spa-Produkte</li><li>Transfer: $4/Person für das Gebiet Hurghada, $5/Person (El Gouna - Sahl Hasheesh - Makadi), $7/Person für Safaga</li></ul>',
                    ],
                    'fr' => [
                        'title' => 'Forfait Cléopâtre Plus',
                        'short_description' => 'Offrez-vous la luxueuse expérience Cléopâtre Plus comprenant une grotte de sel, un sauna, un hammam, un jacuzzi, un gommage traditionnel complet et un massage à la mousse, un peeling à la noix de coco avec masque facial et un massage relaxant de 45 minutes.',
                        'description' => '<h3>Aperçu</h3><p>Offrez-vous l\'ultime voyage spa inspiré de Cléopâtre grâce à notre forfait exclusif Cléopâtre Plus. Cette expérience de bien-être complète associe des rituels de relaxation ancestraux au confort moderne pour une régénération totale. Commencez par la grotte de sel thérapeutique, puis par des séances de sauna et de hammam. Détendez-vous dans le jacuzzi privé apaisant, puis profitez d\'un rituel de Hamam traditionnel complet comprenant un gommage corporel profond, un massage à la mousse riche, un peeling doux à la noix de coco et un masque nourrissant pour le visage. L\'expérience se termine par un massage bienfaisant de 45 minutes de tout le corps pour évacuer le stress et vous laisser rafraîchi et rayonnant. Parfait pour ceux qui recherchent un nettoyage en profondeur, de la détente et une journée de spa luxueuse.</p><h3>Points Forts</h3><ul><li>Séance thérapeutique dans la grotte de sel</li><li>Sauna et hammam pour une désintoxication profonde</li><li>Bain relaxant dans le jacuzzi privé</li><li>Gommage traditionnel, massage à la mousse, peeling à la noix de coco et masque facial</li><li>Massage apaisant de 45 minutes sur tout le corps</li></ul><h3>Inclus</h3><ul><li>Séance en grotte de sel</li><li>Sauna & Hammam</li><li>Jacuzzi privé</li><li>Gommage traditionnel complet & massage à la mousse</li><li>Peeling coco avec masque visage</li><li>Massage professionnel de 45 minutes</li><li>Toutes les serviettes, peignoirs et produits de spa essentiels</li></ul><h3>Exclus</h3><ul><li>Traitements supplémentaires ou prolongation du massage</li><li>Boissons alcoolisées ou haut de gamme</li><li>Produits de spa personnels</li><li>Transfert : 4$ par personne pour la zone de Hurghada, 5$ par personne (El Gouna - Sahl Hasheesh - Makadi), 7$ pour Safaga</li></ul>',
                    ],
                    'ru' => [
                        'title' => 'Пакет Клеопатра Плюс',
                        'short_description' => 'Побалуйте себя роскошной процедурой Cleopatra Plus, включающей соляную пещеру, сауну, паровую баню, джакузи, полный традиционный пилинг и пенный массаж, кокосовый пилинг с маской для лица и расслабляющий 45-минутный массаж.',
                        'description' => '<h3>Обзор</h3><p>Побалуйте себя непревзойденным спа-путешествием в стиле Клеопатры с нашим эксклюзивным пакетом «Клеопатра Плюс». Этот комплексный велнес-опыт сочетает в себе древние ритуалы расслабления и современный комфорт для полного омоложения. Начните с терапевтической соляной пещеры, затем посетите сауну и паровую баню. Расслабьтесь в успокаивающем частном джакузи, а затем насладитесь полным традиционным ритуалом хамама, включающим глубокий пилинг тела, обильный пенный массаж, нежный кокосовый пилинг и питательную маску для лица. Процедура завершается блаженным 45-минутным массажем всего тела, который снимет стресс и подарит вам ощущение свежести и сияния. Идеально подходит для тех, кто ищет глубокое очищение, расслабление и роскошный спа-день.</p><h3>Основные моменты тура</h3><ul><li>Терапевтический сеанс в соляной пещере</li><li>Сауна и паровая баня для глубокой детоксикации</li><li>Расслабляющее купание в приватном джакузи</li><li>Традиционный пилинг, пенный массаж, кокосовый пилинг и маска для лица</li><li>Успокаивающий 45-минутный массаж всего тела</li></ul><h3>В стоимость входит</h3><ul><li>Сеанс в соляной пещере</li><li>Сауна и паровая баня</li><li>Частное джакузи</li><li>Полный традиционный пилинг и пенный массаж</li><li>Кокосовый пилинг с маской для лица</li><li>45-минутный профессиональный массаж</li><li>Все полотенца, халаты и спа-принадлежности</li></ul><h3>В стоимость не входит</h3><ul><li>Дополнительные процедуры или увеличенное время массажа</li><li>Алкогольные или премиальные напитки</li><li>Персональные спа-продукты</li><li>Трансфер: $4 с человека для Хургады, $5 с человека (Эль-Гуна - Сахл Хашиш - Макади), $7 для Сафаги</li></ul>',
                    ],
                    'tr' => [
                        'title' => 'Cleopatra Plus Paketi',
                        'short_description' => 'Tuz mağarası, sauna, buhar odası, jakuzi, geleneksel kese ve köpük masajı, hindistan cevizi peelingi ve yüz maskesi ile 45 dakikalık rahatlatıcı masaj içeren lüks Cleopatra Plus deneyiminin keyfini çıkarın.',
                        'description' => '<h3>Genel Bakış</h3><p>Özel Cleopatra Plus paketimizle kendinizi Cleopatra esintili harika bir spa yolculuğuyla şımartın. Bu kapsamlı sağlık deneyimi, tam bir gençleşme sağlamak için antik rahatlama ritüellerini modern konforla birleştirir. Terapötik Tuz Mağarası ile başlayın, ardından Sauna ve Buhar Odası seanslarıyla devam edin. Rahatlatıcı Özel Jakuzide dinlendikten sonra kese, zengin köpük masajı, yumuşak hindistan cevizi peelingi ve besleyici yüz maskesini içeren tam geleneksel Hamam ritüelinin keyfini çıkarın. Bu eşsiz deneyim, stresi eritmek, sizi yenilemek ve ışıldatmak için 45 dakikalık keyifli bir tam vücut masajı ile sona erer. Derin arınma, rahatlama ve lüks bir spa günü arayanlar için mükemmeldir.</p><h3>Öne Çıkanlar</h3><ul><li>Tuz Mağarasında terapötik seans</li><li>Derin detoksifikasyon için Sauna ve Buhar Odası</li><li>Özel jakuzide rahatlatıcı banyo</li><li>Geleneksel kese, köpük masajı, hindistan cevizi peelingi ve yüz maskesi</li><li>45 dakikalık rahatlatıcı tam vücut masajı</li></ul><h3>Dahil Olanlar</h3><ul><li>Tuz Mağarası seansı</li><li>Sauna & Buhar Odası</li><li>Özel Jakuzi</li><li>Geleneksel Kese & Köpük Masajı</li><li>Hindistan Cevizi Peelingi ve Yüz Maskesi</li><li>45 dakikalık Profesyonel Masaj</li><li>Tüm havlular, bornozlar ve spa gereçleri</li></ul><h3>Hariç Olanlar</h3><ul><li>Ek tedaviler veya uzatılmış masaj süresi</li><li>Alkollü veya premium içecekler</li><li>Kişisel spa ürünleri</li><li>Transfer: Hurghada bölgesi için kişi başı 4$, El Gouna - Sahl Hasheesh - Makadi için kişi başı 5$, Safaga için kişi başı 7$</li></ul>',
                    ],
                    'hi' => [
                        'title' => 'क्लिओपेट्रा प्लस पैकेज',
                        'short_description' => 'शानदार क्लिओपेट्रा प्लस अनुभव का आनंद लें जिसमें नमक की गुफा, सौना, स्टीम रूम, जकूज़ी, पूर्ण पारंपरिक स्क्रब और फोम मालिश, फेस मास्क के साथ नारियल छीलना और आरामदायक 45 मिनट की मालिश शामिल है।',
                        'description' => '<h3>अवलोकन</h3><p>हमारे विशेष क्लिओपेट्रा प्लस पैकेज के साथ खुद को परम क्लिओपेट्रा-प्रेरित स्पा यात्रा पर ले जाएं। यह व्यापक कल्याण अनुभव पूर्ण कायाकल्प के लिए प्राचीन विश्राम अनुष्ठानों को आधुनिक आराम के साथ जोड़ता है। चिकित्सीय नमक गुफा से शुरुआत करें, इसके बाद सौना और स्टीम रूम में सत्र लें। सुखदायक निजी जकूज़ी में आराम करें, फिर एक गहरी बॉडी स्क्रब, समृद्ध फोम मालिश, कोमल नारियल छीलने और एक पौष्टिक फेस मास्क सहित एक पूर्ण पारंपरिक हमाम अनुष्ठान का आनंद लें। तनाव को दूर करने और आपको तरोताजा और चमकदार बनाने के लिए यह अनुभव 45 मिनट की सुखद फुल-बॉडी मालिश के साथ समाप्त होता है। गहरी सफाई, विश्राम और शानदार स्पा दिन चाहने वालों के लिए बिल्कुल सही।</p><h3>मुख्य आकर्षण</h3><ul><li>नमक की गुफा में चिकित्सीय सत्र</li><li>गहरे विषहरण के लिए सौना और स्टीम रूम</li><li>निजी जकूज़ी में आरामदायक स्नान</li><li>पारंपरिक स्क्रब, फोम मसाज, कोकोनट पीलिंग और फेस मास्क</li><li>सुखदायक 45 मिनट की फुल-बॉडी मसाज</li></ul><h3>शामिल है</h3><ul><li>नमक गुफा सत्र</li><li>सौना और स्टीम रूम</li><li>निजी जकूज़ी</li><li>पूर्ण पारंपरिक स्क्रब और फोम मालिश</li><li>फेस मास्क के साथ नारियल छीलना</li><li>45 मिनट की व्यावसायिक मालिश</li><li>सभी तौलिये, गाउन और बुनियादी स्पा आवश्यक चीजें</li></ul><h3>बाहर रखा गया</h3><ul><li>अठिरिक्त मालिश समय या उपचार</li><li>मादक या प्रीमियम पेय</li><li>व्यक्तिगत स्पा उत्पाद</li><li>स्थानांतरण: हुर्गदा क्षेत्र के लिए $4 प्रति व्यक्ति, $5 प्रति व्यक्ति (एल-गोना - साहल हशीश - मकाडी), $7 सफागा</li></ul>',
                    ]
                ]
            ],
            [
                'title' => 'Hamam + Massage 45 Package',
                'slug' => 'hamam-plus-massage-45-package',
                'duration_minutes' => 90,
                'price' => 23.00,
                'gender_type' => 'both',
                'status' => 1,
                'short_description' => 'Relax and rejuvenate with our Hamam + Massage package. Enjoy the salt cave, sauna, steam room, jacuzzi, a full traditional scrub & foam massage, plus a soothing 45-minute massage.',
                'description' => '<h3>Overview</h3><p>Discover deep relaxation with our popular Hamam + Massage package. This comprehensive spa experience combines traditional Turkish bath rituals with modern wellness treatments for total body and mind renewal. Your session begins in the therapeutic Salt Cave, followed by the Sauna and Steam Room to open the pores and detoxify. Then unwind in the warm Jacuzzi before moving to the authentic Hamam for a thorough body scrub and rich foam massage. The experience is completed with a relaxing 45-minute full-body massage that melts away tension and leaves you refreshed and revitalized. Ideal for those looking for a complete, luxurious, and deeply cleansing spa treatment.</p><h3>Trip Highlights</h3><ul><li>Therapeutic session in the Salt Cave for natural detoxification</li><li>Sauna and Steam Room to relax muscles and cleanse the skin</li><li>Soothing soak in the jacuzzi</li><li>Traditional Hamam scrub and foam massage</li><li>Relaxing 45-minute professional full-body massage</li></ul><h3>Includes</h3><ul><li>Salt Cave session</li><li>Sauna & Steam Room</li><li>Jacuzzi session</li><li>Traditional Scrub & Foam Massage</li><li>45-minute Professional Massage</li><li>All towels, robes, and spa amenities</li></ul><h3>Excludes</h3><ul><li>Coconut peeling and face mask (available in higher packages)</li><li>Additional massage time or treatments</li><li>Alcoholic or premium beverages</li><li>Personal spa products</li><li>Transfer: $4/pax for Hurghada area, $5/pax for El Gouna/Sahl Hasheesh/Makadi, $7/pax for Safaga</li></ul>',
                'translations' => [
                    'ar' => [
                        'title' => 'باقة حمام + مساج 45 دقيقة',
                        'short_description' => 'استرح وجدد نشاطك مع باقة الحمام والمساج الخاصة بنا. استمتع بكهف الملح، الساونا، غرفة البخار، الجاكوزي، التقشير التقليدي الكامل والمساج بالرغوة، بالإضافة إلى مساج مهدئ لمدة 45 دقيقة.',
                        'description' => '<h3>نظرة عامة</h3><p>اكتشف الاسترخاء العميق مع باقة الحمام والمساج الشهيرة. تجمع تجربة السبا الشاملة هذه بين طقوس الحمام التركي التقليدي وعلاجات العافية الحديثة لتجديد الجسم والعقل بالكامل. تبدأ جلستك في كهف الملح العلاجي، تليها الساونا وغرفة البخار لفتح المسام والتخلص من السموم. بعد ذلك، استرخِ في الجاكوزي الدافئ قبل الانتقال إلى الحمام الأصيل للحصول على تقشير شامل للجسم ومساج بالرغوة الغنية. تكتمل التجربة بمساج مريح للجسم بالكامل لمدة 45 دقيقة يزيل التوتر ويتركك منتعشًا ومتجدد النشاط. مثالي لمن يبحثون عن علاج سبا كامل وفاخر ومطهر بعمق.</p><h3>أبرز مميزات الرحلة</h3><ul><li>جلسة علاجية في كهف الملح للتخلص من السموم طبيعياً</li><li>ساونا وغرفة بخار لتهدئة العضلات وتنظيف البشرة</li><li>نقع مهدئ في الجاكوزي</li><li>تقشير حمام تقليدي ومساج بالرغوة</li><li>مساج احترافي مهدئ للجسم بالكامل لمدة 45 دقيقة</li></ul><h3>يشتمل على</h3><ul><li>جلسة كهف الملح</li><li>ساونا وغرفة بخار</li><li>جلسة جاكوزي</li><li>تقشير كامل ومساج بالرغوة تقليدي</li><li>مساج احترافي لمدة 45 دقيقة</li><li>جميع المناشف والأرواب ومستلزمات السبا</li></ul><h3>لا يشتمل على</h3><ul><li>تقشير جوز الهند وقناع الوجه (متوفر في الباقات الأعلى)</li><li>وقت مساج إضافي أو علاجات إضافية</li><li>المشروبات الكحولية أو الفاخرة</li><li>منتجات السبا الشخصية</li><li>الانتقالات: 4 دولارات للفرد لمنطقة الغردقة، 5 دولارات للفرد (الجونة - سهل حشيش - مكادي)، 7 دولارات لسفاجا</li></ul>',
                    ],
                    'de' => [
                        'title' => 'Hamam + Massage 45 Paket',
                        'short_description' => 'Entspannen und verjüngen Sie sich mit unserem Hamam + Massage Paket. Genießen Sie die Salzgrotte, Sauna, Dampfbad, Whirlpool, eine traditionelle Peeling- & Schaummassage sowie eine wohltuende 45-minütige Massage.',
                        'description' => '<h3>Überblick</h3><p>Entdecken Sie tiefe Entspannung mit unserem beliebten Hamam + Massage-Paket. Dieses umfassende Wellness-Erlebnis kombiniert traditionelle türkische Bad-Rituale mit modernen Wellness-Behandlungen für eine totale Erneuerung von Körper und Geist. Ihre Sitzung beginnt in der therapeutischen Salzgrotte, gefolgt von Sauna und Dampfbad, um die Poren zu öffnen und zu entgiften. Entspannen Sie sich anschließend im warmen Whirlpool, bevor Sie sich in das authentische Hamam begeben, wo Sie ein gründliches Körperpeeling und eine reichhaltige Schaummassage erwarten. Das Erlebnis wird durch eine entspannende 45-minütige Ganzkörpermassage abgerundet, die Verspannungen löst und Sie erfrischt und revitalisiert zurücklässt. Ideal für alle, die eine komplette, luxuriöse und tiefenreinigende Spa-Behandlung suchen.</p><h3>Highlights</h3><ul><li>Therapeutische Sitzung in der Salzgrotte zur natürlichen Entgiftung</li><li>Sauna und Dampfbad zur Muskelentspannung und Hautreinigung</li><li>Wohltuendes Bad im Whirlpool</li><li>Traditionelles Hamam-Peeling und Schaummassage</li><li>Entspannende 45-minütige professionelle Ganzkörpermassage</li></ul><h3>Inklusive</h3><ul><li>Sitzung in der Salzgrotte</li><li>Sauna & Dampfbad</li><li>Whirlpool-Sitzung</li><li>Traditionelle Peeling- & Schaummassage</li><li>45-minütige professionelle Massage</li><li>Alle Handtücher, Bademäntel und Spa-Annehmlichkeiten</li></ul><h3>Exklusive</h3><ul><li>Kokospeeling und Gesichtsmaske (in höheren Paketen erhältlich)</li><li>Zusätzliche Massagezeit oder Behandlungen</li><li>Alkoholische Getränke oder Premium-Getränke</li><li>Persönliche Spa-Produkte</li><li>Transfer: $4/Person für das Gebiet Hurghada, $5/Person (El Gouna - Sahl Hasheesh - Makadi), $7/Person für Safaga</li></ul>',
                    ],
                    'fr' => [
                        'title' => 'Forfait Hamam + Massage 45',
                        'short_description' => 'Détendez-vous et ressourcez-vous grâce à notre forfait Hamam + Massage. Profitez de la grotte de sel, du sauna, du hammam, du jacuzzi, d\'un gommage traditionnel complet et d\'un massage à la mousse, plus un massage apaisant de 45 minutes.',
                        'description' => '<h3>Aperçu</h3><p>Découvrez une relaxation profonde grâce à notre forfait populaire Hamam + Massage. Cette expérience de spa complète associe les rituels traditionnels du bain turc à des soins de bien-être modernes pour un renouvellement total du corps et de l\'esprit. Votre séance commence dans la grotte de sel thérapeutique, suivie du sauna et du hammam pour ouvrir les pores et éliminer les toxines. Détendez-vous ensuite dans le jacuzzi chaud avant de vous rendre dans le Hamam authentique pour un gommage corporel complet et un massage riche en mousse. L\'expérience est complétée par un massage relaxant de 45 minutes du corps entier qui dissipe les tensions et vous laisse rafraîchi et revitalisé. Idéal pour ceux qui recherchent un traitement de spa complet, luxueux et nettoyant en profondeur.</p><h3>Points Forts</h3><ul><li>Séance thérapeutique dans la grotte de sel pour une désintoxication naturelle</li><li>Sauna et hammam pour détendre les muscles et nettoyer la peau</li><li>Bain apaisant dans le jacuzzi</li><li>Gommage traditionnel du hammam et massage à la mousse</li><li>Massage relaxant professionnel complet du corps de 45 minutes</li></ul><h3>Inclus</h3><ul><li>Séance en grotte de sel</li><li>Sauna & Hammam</li><li>Séance de jacuzzi</li><li>Gommage traditionnel & massage à la mousse</li><li>Massage professionnel de 45 minutes</li><li>Toutes les serviettes, peignoirs et produits de spa</li></ul><h3>Exclus</h3><ul><li>Peeling à la noix de coco et masque facial (disponibles dans les forfaits supérieurs)</li><li>Temps de massage ou traitements supplémentaires</li><li>Boissons alcoolisées ou premium</li><li>Produits de spa personnels</li><li>Transfert : 4$ par personne pour la zone de Hurghada, 5$ par personne (El Gouna - Sahl Hasheesh - Makadi), 7$ pour Safaga</li></ul>',
                    ],
                    'ru' => [
                        'title' => 'Пакет Хамам + Массаж 45',
                        'short_description' => 'Расслабьтесь и омолодитесь с нашим пакетом «Хамам + Массаж». Вас ждут соляная пещера, сауна, паровая баня, джакузи, традиционный пилинг и пенный массаж, а также расслабляющий 45-минутный массаж.',
                        'description' => '<h3>Обзор</h3><p>Откройте для себя глубокое расслабление с нашим популярным пакетом «Хамам + Массаж». Этот комплексный спа-опыт сочетает в себе традиционные ритуалы турецкой бани с современными оздоровительными процедурами для полного обновления тела и разума. Ваш сеанс начнется в терапевтической соляной пещере, после чего вы посетите сауну и паровую баню, чтобы открыть поры и вывести токсины. Затем расслабьтесь в теплом джакузи, прежде чем перейти в аутентичный хамам для тщательного пилинга тела и обильного пенного массажа. Процедура завершается расслабляющим 45-минутным массажем всего тела, который снимает напряжение и дарит вам ощущение свежести и сил. Идеально подходит для тех, кто ищет полноценный, роскошный и глубоко очищающий спа-уход.</p><h3>Основные моменты тура</h3><ul><li>Терапевтический сеанс в соляной пещере для естественной детоксикации</li><li>Сауна и паровая баня для расслабления мышц и очищения кожи</li><li>Успокаивающее расслабление в джакузи</li><li>Традиционный пилинг в хамаме и пенный массаж</li><li>Расслабляющий 45-минутный профессиональный массаж всего тела</li></ul><h3>В стоимость входит</h3><ul><li>Сеанс в соляной пещере</li><li>Сауна и паровая баня</li><li>Сеанс в джакузи</li><li>Традиционный пилинг и пенный массаж</li><li>45-минутный профессиональный массаж</li><li>Все полотенца, халаты и спа-принадлежности</li></ul><h3>В стоимость не входит</h3><ul><li>Кокосовый пилинг и маска для лица (доступны в более дорогих пакетах)</li><li>Дополнительное время массажа или процедуры</li><li>Алкогольные или премиальные напитки</li><li>Персональные спа-продукты</li><li>Трансфер: $4 с человека для Хургады, $5 с человека (Эль-Гуна - Сахл Хашиш - Макади), $7 для Сафаги</li></ul>',
                    ],
                    'tr' => [
                        'title' => 'Hamam + Masaj 45 Paketi',
                        'short_description' => 'Hamam + Masaj paketimizle rahatlayın ve gençleşin. Tuz mağarası, sauna, buhar odası, jakuzi, geleneksel kese & köpük masajı ve 45 dakikalık rahatlatıcı masajın keyfini çıkarın.',
                        'description' => '<h3>Genel Bakış</h3><p>Popüler Hamam + Masaj paketimizle derin bir rahatlama keşfedin. Bu kapsamlı spa deneyimi, beden ve zihnin tamamen yenilenmesi için geleneksel Türk hamamı ritüellerini modern sağlık uygulamalarıyla birleştirir. Seansınız terapötik Tuz Mağarasında başlar, ardından gözenekleri açmak ve detoks yapmak için Sauna ve Buhar Odası ile devam eder. Ardından sıcak Jakuzide rahatlayıp derin bir vücut kesesi ve zengin köpük masajı için otantik Hamama geçin. Bu harika yolculuk, tüm gerginliği yok eden ve sizi yenileyip canlandıran 45 dakikalık rahatlatıcı bir tam vücut masajı ile tamamlanır. Eksiksiz, lüks ve derinlemesine arındırıcı bir spa bakımı arayanlar için idealdir.</p><h3>Öne Çıkanlar</h3><ul><li>Doğal detoks için Tuz Mağarasında terapötik seans</li><li>Kasları gevşetmek ve cildi temizlemek için Sauna ve Buhar Odası</li><li>Jakuzide rahatlatıcı banyo keyfi</li><li>Geleneksel Hamam kesesi ve köpük masajı</li><li>45 dakikalık rahatlatıcı profesyonel tam vücut masajı</li></ul><h3>Dahil Olanlar</h3><ul><li>Tuz Mağarası seansı</li><li>Sauna & Buhar Odası</li><li>Jakuzi seansı</li><li>Geleneksel Kese & Köpük Masajı</li><li>45 dakikalık Profesyonel Masaj</li><li>Tüm havlular, bornozlar ve spa gereçleri</li></ul><h3>Hariç Olanlar</h3><ul><li>Hindistan cevizi peelingi ve yüz maskesi (daha yüksek paketlerde mevcuttur)</li><li>Ek masaj süresi veya tedaviler</li><li>Alkollü veya premium içecekler</li><li>Kişisel spa ürünleri</li><li>Transfer: Hurghada bölgesi için kişi başı 4$, El Gouna - Sahl Hasheesh - Makadi için kişi başı 5$, Safaga için kişi başı 7$</li></ul>',
                    ],
                    'hi' => [
                        'title' => 'हमाम + मसाज 45 पैकेज',
                        'short_description' => 'हमारे हमाम + मसाज पैकेज के साथ आराम करें और तरोताजा हो जाएं। नमक की गुफा, सौना, स्टीम रूम, जकूज़ी, पूर्ण पारंपरिक स्क्रब और फोम मालिश, साथ ही सुखदायक 45 मिनट की मालिश का आनंद लें।',
                        'description' => '<h3>अवलोकन</h3><p>हमारे लोकप्रिय हमाम + मसाज पैकेज के साथ गहरे विश्राम की खोज करें। यह व्यापक स्पा अनुभव शरीर और दिमाग के संपूर्ण नवीनीकरण के लिए पारंपरिक तुर्की स्नान अनुष्ठानों को आधुनिक कल्याण उपचारों के साथ जोड़ता है। आपका सत्र चिकित्सीय नमक गुफा से शुरू होता है, इसके बाद छिद्रों को खोलने और विषमुक्त करने के लिए सौना और स्टीम रूम होता. फिर एक गहन बॉडी स्क्रब और समृद्ध फोम मसाज के लिए प्रामाणिक हमाम में जाने से पहले गर्म जकूज़ी में आराम करें। अनुभव 45 मिनट की आरामदायक फुल-बॉडी मालिश के साथ पूरा होता है जो तनाव को दूर करता है और आपको तरोताजा और पुनर्जीवित महसूस कराता है। पूर्ण, शानदार और गहरी सफाई वाले स्पा उपचार की तलाश करने वालों के लिए आदर्श।</p><h3>मुख्य आकर्षण</h3><ul><li>प्राकृतिक विषहरण के लिए नमक की गुफा में चिकित्सीय सत्र</li><li>मांसपेशियों को आराम देने और त्वचा को साफ करने के लिए सौना और स्टीम रूम</li><li>जकूज़ी में सुखदायक स्नान</li><li>पारंपरिक हमाम स्क्रब और फोम मालिश</li><li>आरामदायक 45 मिनट की पेशेवर फुल-बॉडी मसाज</li></ul><h3>शामिल है</h3><ul><li>नमक गुफा सत्र</li><li>सौना और स्टीम रूम</li><li>जकूज़ी सत्र</li><li>पारंपरिक स्क्रब और फोम मालिश</li><li>45 मिनट की व्यावसायिक मालिश</li><li>सभी तौलिये, गाउन और स्पा सुविधाएं</li></ul><h3>बाहर रखा गया</h3><ul><li>नारियल छीलना और फेस मास्क (उच्च पैकेजों में उपलब्ध)</li><li>अतिरिक्त मालिश समय या उपचार</li><li>मादक या प्रीमियम पेय</li><li>व्यक्तिगत स्पा उत्पाद</li><li>स्थानांतरण: हुर्गदा क्षेत्र के लिए $4 प्रति व्यक्ति, $5 प्रति व्यक्ति (एल-गोना - साहल हशीश - मकाडी), $7 सफागा</li></ul>',
                    ]
                ]
            ],
            [
                'title' => 'Hamam + Massage 60 Package',
                'slug' => 'hamam-plus-massage-60-package',
                'duration_minutes' => 120,
                'price' => 26.00,
                'gender_type' => 'both',
                'status' => 1,
                'short_description' => 'Relax and rejuvenate with our Hamam + Massage package. Enjoy the Salt Cave, Sauna, Steam Room, Jacuzzi, traditional scrub & foam massage, plus a full 60-minute massage for complete relaxation.',
                'description' => '<h3>Overview</h3><p>Experience the perfect blend of traditional Turkish bath rituals and modern wellness in our Hamam + Massage package. This soothing spa journey begins with a therapeutic session in the Salt Cave, followed by the heat of the Sauna and Steam Room. Unwind in the warm Jacuzzi, then indulge in a full authentic Hamam experience featuring a deep body scrub and rich foam massage. The package concludes with a long, relaxing 60-minute full-body massage that melts away tension and restores your energy. Ideal for those looking for a comprehensive and deeply restorative spa treatment.</p><h3>Trip Highlights</h3><ul><li>Therapeutic session in the Salt Cave</li><li>Sauna and Steam Room for detoxification and relaxation</li><li>Soothing soak in the private jacuzzi</li><li>Traditional body scrub and foam massage in the Hamam</li><li>Extended 60-minute full-body professional massage</li></ul><h3>Includes</h3><ul><li>Salt Cave session</li><li>Sauna & Steam Room</li><li>Private Jacuzzi</li><li>Traditional Scrub & Foam Massage</li><li>60-minute Professional Full-Body Massage</li><li>All towels, robes, and basic spa amenities</li></ul><h3>Excludes</h3><ul><li>Additional treatments or massage extensions</li><li>Alcoholic or premium beverages</li><li>Personal spa products</li><li>Transfer: $4/pax for Hurghada area, $5/pax for El Gouna/Sahl Hasheesh/Makadi, $7/pax for Safaga</li></ul>',
                'translations' => [
                    'ar' => [
                        'title' => 'باقة حمام + مساج 60 دقيقة',
                        'short_description' => 'استرح وجدد نشاطك مع باقة الحمام والمساج الخاصة بنا. استمتع بكهف الملح، الساونا، غرفة البخار، الجاكوزي، التقشير التقليدي والمساج بالرغوة، بالإضافة إلى مساج كامل لمدة 60 دقيقة للاسترخاء التام.',
                        'description' => '<h3>نظرة عامة</h3><p>اكتشف المزيج المثالي بين طقوس الحمام التركي التقليدي والعافية الحديثة في باقة الحمام والمساج. تبدأ هذه الرحلة المهدئة في السبا بجلسة علاجية في كهف الملح، تليها حرارة الساونا وغرفة البخار. استرخِ في الجاكوزي الدافئ، ثم استمتع بتجربة حمام كاملة وأصيلة تتميز بتقشير عميق للجسم ومساج بالرغوة الغنية. وتختتن الباقة بمساج طويل ومريح للجسم بالكامل لمدة 60 دقيقة يزيل التوتر ويعيد إليك طاقتك. مثالي لمن يبحثون عن علاج سبا شامل ومجدد للنشاط بعمق.</p><h3>أبرز مميزات الرحلة</h3><ul><li>جلسة علاجية في كهف الملح</li><li>ساونا وغرفة بخار للتخلص من السموم والاسترخاء</li><li>نقع مهدئ في الجاكوزي الخاص</li><li>تقشير تقليدي للجسم ومساج بالرغوة في الحمام</li><li>مساج احترافي ممتد للجسم بالكامل لمدة 60 دقيقة</li></ul><h3>يشتمل على</h3><ul><li>جلسة كهف الملح</li><li>ساونا وغرفة بخار</li><li>جاكوزي خاص</li><li>تقشير كامل ومساج بالرغوة تقليدي</li><li>مساج احترافي كامل للجسم لمدة 60 دقيقة</li><li>جميع المناشف والأرواب ومستلزمات السبا الأساسية</li></ul><h3>لا يشتمل على</h3><ul><li>علاجات إضافية أو وقت مساج إضافي</li><li>المشروبات الكحولية أو الفاخرة</li><li>منتجات السبا الشخصية</li><li>الانتقالات: 4 دولارات للفرد لمنطقة الغردقة، 5 دولارات للفرد (الجونة - سهل حشيش - مكادي)، 7 دولارات لسفاجا</li></ul>',
                    ],
                    'de' => [
                        'title' => 'Hamam + Massage 60 Paket',
                        'short_description' => 'Entspannen und verjüngen Sie sich mit unserem Hamam + Massage Paket. Genießen Sie die Salzgrotte, Sauna, Dampfbad, Whirlpool, traditionelle Peeling- & Schaummassage sowie eine 60-minütige Massage für vollkommene Entspannung.',
                        'description' => '<h3>Überblick</h3><p>Erleben Sie die perfekte Mischung aus traditionellen türkischen Bad-Ritualen und moderner Wellness in unserem Hamam + Massage-Paket. Diese wohltuende Spa-Reise beginnt mit einer therapeutischen Sitzung in der Salzgrotte, gefolgt von der Hitze der Sauna und des Dampfbads. Entspannen Sie sich im warmen Whirlpool und genießen Sie anschließend ein umfassendes, authentisches Hamam-Erlebnis mit einem tiefen Körperpeeling und einer reichhaltigen Schaummassage. Das Paket endet mit einer langen, entspannenden 60-minütigen Ganzkörpermassage, die Verspannungen löst und Ihre Energie wieder aufbaut. Ideal für alle, die eine umfassende und tiefenwirksame Erholung suchen.</p><h3>Highlights</h3><ul><li>Therapeutische Sitzung in der Salzgrotte</li><li>Sauna und Dampfbad zur Entgiftung und Entspannung</li><li>Wohltuendes Bad im privaten Whirlpool</li><li>Traditionelles Körperpeeling und Schaummassage im Hamam</li><li>Verlängerte 60-minütige professionelle Ganzkörpermassage</li></ul><h3>Inklusive</h3><ul><li>Sitzung in der Salzgrotte</li><li>Sauna & Dampfbad</li><li>Privater Whirlpool</li><li>Traditionelle Peeling- & Schaummassage</li><li>60-minütige professionelle Ganzkörpermassage</li><li>Alle Handtücher, Bademäntel und grundlegenden Spa-Annehmlichkeiten</li></ul><h3>Exklusive</h3><ul><li>Zusätzliche Behandlungen oder Verlängerungen der Massage</li><li>Alkoholische Getränke oder Premium-Getränke</li><li>Persönliche Spa-Produkte</li><li>Transfer: $4/Person für das Gebiet Hurghada, $5/Person (El Gouna - Sahl Hasheesh - Makadi), $7/Person für Safaga</li></ul>',
                    ],
                    'fr' => [
                        'title' => 'Forfait Hamam + Massage 60',
                        'short_description' => 'Détendez-vous et ressourcez-vous grâce à notre forfait Hamam + Massage. Profitez de la grotte de sel, du sauna, du hammam, du jacuzzi, du gommage traditionnel et du massage à la mousse, plus un massage complet de 60 minutes pour une relaxation totale.',
                        'description' => '<h3>Aperçu</h3><p>Découvrez l\'alliance parfaite des rituels traditionnels du bain turc et du bien-être moderne dans notre forfait Hamam + Massage. Ce voyage apaisant commence par une séance thérapeutique dans la grotte de sel, suivie par la chaleur du sauna et du hammam. Détendez-vous dans le jacuzzi chaud, puis offrez-vous une expérience de Hamam authentique et complète, comprenant un gommage profond du corps et un massage riche en mousse. Le forfait se termine par un long massage relaxant de 60 minutes sur l\'ensemble du corps, qui dissipe les tensions et rétablit votre énergie. Idéal pour ceux qui recherchent un traitement de spa complet et profondément réparateur.</p><h3>Points Forts</h3><ul><li>Séance thérapeutique dans la grotte de sel</li><li>Sauna et hammam pour la désintoxication et la relaxation</li><li>Bain apaisant dans le jacuzzi privé</li><li>Gommage traditionnel du corps et massage à la mousse dans le Hamam</li><li>Massage professionnel complet du corps prolongé de 60 minutes</li></ul><h3>Inclus</h3><ul><li>Séance en grotte de sel</li><li>Sauna & Hammam</li><li>Jacuzzi privé</li><li>Gommage traditionnel & massage à la mousse</li><li>Massage complet du corps professionnel de 60 minutes</li><li>Toutes les serviettes, peignoirs et produits de spa de base</li></ul><h3>Exclus</h3><ul><li>Soins supplémentaires ou extensions de massage</li><li>Boissons alcoolisées ou premium</li><li>Produits de spa personnels</li><li>Transfert : 4$ par personne pour la zone de Hurghada, 5$ par personne (El Gouna - Sahl Hasheesh - Makadi), 7$ pour Safaga</li></ul>',
                    ],
                    'ru' => [
                        'title' => 'Пакет Хамам + Массаж 60',
                        'short_description' => 'Расслабьтесь и омолодитесь с нашим пакетом «Хамам + Массаж». Насладитесь соляной пещерой, сауной, паровой баней, джакузи, традиционным пилингом и пенным массажем, а также полноценным 60-минутным массажем для полного расслабления.',
                        'description' => '<h3>Обзор</h3><p>Испытайте идеальное сочетание традиционных ритуалов турецкой бани и современного велнеса в нашем пакете «Хамам + Массаж». Это успокаивающее спа-путешествие начинается с терапевтического сеанса в соляной пещере, после чего вас ждут горячая сауна и паровая баня. Отдохните в теплом джакузи, а затем побалуйте себя полноценной процедурой в хамаме с глубоким пилингом тела и обильным пенным массажем. Пакет завершается длительным расслабляющим 60-минутным массажем всего тела, который снимет напряжение и восстановит силы. Идеально подходит для тех, кто ищет всестороннее и глубоко восстанавливающее спа-лечение.</p><h3>Основные моменты тура</h3><ul><li>Терапевтический сеанс в соляной пещере</li><li>Сауна и паровая баня для детоксикации и релаксации</li><li>Успокаивающее купание в приватном джакузи</li><li>Традиционный пилинг тела и пенный массаж в хамаме</li><li>Увеличенный 60-минутный профессиональный массаж всего тела</li></ul><h3>В стоимость входит</h3><ul><li>Сеанс в соляной пещере</li><li>Сауна и паровая баня</li><li>Приватное джакузи</li><li>Традиционный пилинг и пенный массаж</li><li>60-минутный профессиональный массаж всего тела</li><li>Все полотенца, халаты и базовые спа-принадлежности</li></ul><h3>В стоимость не входит</h3><ul><li>Дополнительные процедуры или продление массажа</li><li>Алкогольные или премиальные напитки</li><li>Персональные спа-продукты</li><li>Трансфер: $4 с человека для Хургады, $5 с человека (Эль-Гуна - Сахл Хашиш - Макади), $7 для Сафаги</li></ul>',
                    ],
                    'tr' => [
                        'title' => 'Hamam + Masaj 60 Paketi',
                        'short_description' => 'Hamam + Masaj paketimizle rahatlayın ve yenilenin. Tuz mağarası, sauna, buhar odası, jakuzi, geleneksel kese & köpük masajı ve tam rahatlama için 60 dakikalık masajın keyfini çıkarın.',
                        'description' => '<h3>Genel Bakış</h3><p>Hamam + Masaj paketimizde geleneksel Türk hamamı ritüelleri ile modern sağlığın mükemmel uyumunu deneyimleyin. Bu rahatlatıcı spa yolculuğu, Tuz Mağarasında terapötik seansla başlar, ardından Sauna ve Buhar Odasının sıcaklığı ile devam eder. Sıcak Jakuzide dinlendikten sonra derin vücut kesesi ve zengin köpük masajı içeren eksiksiz ve otantik Hamam deneyimiyle kendinizi şımartın. Paket, tüm gerginliği yok eden ve enerjinizi geri kazandıran 60 dakikalık uzun ve rahatlatıcı bir tam vücut masajı ile sona erer. Kapsamlı ve derinlemesine canlandırıcı bir spa bakımı arayanlar için hesaplıdır.</p><h3>Öne Çıkanlar</h3><ul><li>Tuz Mağarasında terapötik seans</li><li>Detoksifikasyon ve rahatlama için Sauna ve Buhar Odası</li><li>Özel jakuzide rahatlatıcı banyo</li><li>Hamamda geleneksel vücut kesesi ve köpük masajı</li><li>Uzun süreli 60 dakikalık profesyonel tam vücut masajı</li></ul><h3>Dahil Olanlar</h3><ul><li>Tuz Mağarası seansı</li><li>Sauna & Buhar Odası</li><li>Özel Jakuzi</li><li>Geleneksel Kese & Köpük Masajı</li><li>60 dakikalık Profesyonel Tam Vücut Masajı</li><li>Tüm havlular, bornozlar ve temel spa gereçleri</li></ul><h3>Hariç Olanlar</h3><ul><li>Ek tedaviler veya masaj uzatmaları</li><li>Alkollü veya premium içecekler</li><li>Kişisel spa ürünleri</li><li>Transfer: Hurghada bölgesi için kişi başı 4$, El Gouna - Sahl Hasheesh - Makadi için kişi başı 5$, Safaga için kişi başı 7$</li></ul>',
                    ],
                    'hi' => [
                        'title' => 'हमाम + मसाज 60 पैकेज',
                        'short_description' => 'हमारे हमाम + मसाज पैकेज के साथ आराम करें और तरोताजा हो जाएं। नमक की गुफा, सौना, स्टीम रूम, जकूज़ी, पारंपरिक स्क्रब और फोम मालिश, साथ ही पूर्ण विश्राम के लिए पूरे 60 मिनट की मालिश का आनंद लें।',
                        'description' => '<h3>अवलोकन</h3><p>हमारे हमाम + मसाज पैकेज में पारंपरिक तुर्की स्नान अनुष्ठानों और आधुनिक कल्याण के सही मिश्रण का अनुभव करें। यह सुखदायक स्पा यात्रा नमक की गुफा में चिकित्सीय सत्र के साथ शुरू होती है, इसके बाद सौना और स्टीम रूम की गर्मी होती है। गर्म जकूज़ी में आराम करें, फिर एक गहरी बॉडी स्क्रब और समृद्ध फोम मालिश की विशेषता वाले एक पूर्ण प्रामाणिक हमाम अनुभव का आनंद लें। पैकेज 60 मिनट की लंबी, आरामदायक फुल-बॉडी मालिश के साथ समाप्त होता है जो तनाव को दूर करता है और आपकी ऊर्जा को बहाल करता है। एक व्यापक और गहराई से बहाल करने वाले स्पा उपचार की तलाश करने वालों के लिए आदर्श।</p><h3>मुख्य आकर्षण</h3><ul><li>नमक की गुफा में चिकित्सीय सत्र</li><li>विषहरण और विश्राम के लिए सौना और स्टीम रूम</li><li>निजी जकूज़ी में आरामदायक स्नान</li><li>हमाम में पारंपरिक बॉडी स्क्रब और फोम मालिश</li><li>विस्तारित 60 मिनट की फुल-बॉडी पेशेवर मालिश</li></ul><h3>शामिल है</h3><ul><li>नमक गुफा सत्र</li><li>सौना और स्टीम रूम</li><li>निजी जकूज़ी</li><li>पारंपरिक स्क्रब और फोम मालिश</li><li>60 मिनट की व्यावसायिक फुल-बॉडी मसाज</li><li>सभी तौलिये, गाउन और बुनियादी स्पा सुविधाएं</li></ul><h3>बाहर रखा गया</h3><ul><li>अतिरिक्त उपचार या मालिश विस्तार</li><li>मादक या प्रीमियम पेय</li><li>व्यक्तिगत स्पा उत्पाद</li><li>स्थानांतरण: हुर्गदा क्षेत्र के लिए $4 प्रति व्यक्ति, $5 प्रति व्यक्ति (एल-गोना - साहल हशीश - मकाडी), $7 सफागा</li></ul>',
                    ]
                ]
            ],
        ];

        foreach ($packages as $pkg) {
            $translations = $pkg['translations'];
            unset($pkg['translations']);

            // Idempotency: check if slug already exists
            $existing = DB::table('spa_services')->where('slug', $pkg['slug'])->first();
            if ($existing) {
                $this->command->info("SPA Service with slug '{$pkg['slug']}' already exists, skipping.");
                continue;
            }

            // Insert into spa_services
            $spaServiceId = DB::table('spa_services')->insertGetId([
                'title' => $pkg['title'],
                'slug' => $pkg['slug'],
                'description' => $pkg['description'],
                'short_description' => $pkg['short_description'],
                'image' => null,
                'duration_minutes' => $pkg['duration_minutes'],
                'price' => $pkg['price'],
                'price_note' => null,
                'location' => 'Egypt',
                'gender_type' => $pkg['gender_type'],
                'available_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
                'available_time_from' => '10:00:00',
                'available_time_to' => '22:00:00',
                'max_guests_per_slot' => 4,
                'sort_order' => 0,
                'status' => $pkg['status'],
                'meta_title' => $pkg['title'],
                'meta_description' => $pkg['short_description'],
                'created_at' => now(),
                'updated_at' => now()
            ]);

            // Default English Translation
            DB::table('spa_service_translations')->insert([
                'spa_service_id' => $spaServiceId,
                'lang_code' => 'en',
                'title' => $pkg['title'],
                'description' => $pkg['description'],
                'short_description' => $pkg['short_description'],
                'price_note' => null,
                'location' => 'Egypt',
                'meta_title' => $pkg['title'],
                'meta_description' => $pkg['short_description'],
                'created_at' => now(),
                'updated_at' => now()
            ]);

            // Other language translations
            foreach ($translations as $locale => $trans) {
                DB::table('spa_service_translations')->insert([
                    'spa_service_id' => $spaServiceId,
                    'lang_code' => $locale,
                    'title' => $trans['title'],
                    'description' => $trans['description'],
                    'short_description' => $trans['short_description'],
                    'price_note' => null,
                    'location' => 'Egypt',
                    'meta_title' => $trans['title'],
                    'meta_description' => $trans['short_description'],
                    'created_at' => now(),
                    'updated_at' => now()
                ]);
            }

            $this->command->info("Successfully seeded SPA Service: {$pkg['title']}");
        }
    }
}
